services:
  api:
    build:
      context: ..
      dockerfile: fluxer_api/Dockerfile
      cache_from:
        - type=gha,scope=api
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=api
    image: fluxer-e2e/fluxer-api:local

  app-proxy:
    build:
      context: ..
      dockerfile: fluxer_app_proxy/Dockerfile
      args:
        PRECOMPRESS_BROTLI_QUALITY: "4"
      cache_from:
        - type=gha,scope=app-proxy
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=app-proxy
    image: fluxer-e2e/fluxer-app-proxy-self-hosted:local

  messages:
    build:
      context: ..
      dockerfile: fluxer_messages/Dockerfile
      cache_from:
        - type=gha,scope=messages
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=messages
    image: fluxer-e2e/fluxer-messages:local

  static-proxy:
    build:
      context: ..
      dockerfile: fluxer_static/Dockerfile
      cache_from:
        - type=gha,scope=static-proxy
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=static-proxy
    image: fluxer-e2e/fluxer-static:local

  snowflakes:
    build:
      context: ..
      dockerfile: fluxer_snowflakes/Dockerfile
      cache_from:
        - type=gha,scope=snowflakes
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=snowflakes
    image: fluxer-e2e/fluxer-snowflakes:local

  users:
    build:
      context: ..
      dockerfile: fluxer_users/Dockerfile
      cache_from:
        - type=gha,scope=users
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=users
    image: fluxer-e2e/fluxer-users:local

  media-proxy:
    build:
      context: ..
      dockerfile: fluxer_media_proxy/Dockerfile
      cache_from:
        - type=gha,scope=media-proxy
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=media-proxy
    image: fluxer-e2e/fluxer-media-proxy:local

  gateway:
    build:
      context: ..
      dockerfile: fluxer_gateway/Dockerfile
      cache_from:
        - type=gha,scope=gateway
      cache_to:
        - type=gha,mode=max,ignore-error=true,scope=gateway
    image: fluxer-e2e/fluxer-gateway:local
